# SPDX-FileCopyrightText: 2006-2025, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2025, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Lint2

on:
  pull_request:

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  cancel_linux:
    name: Dump
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        run: echo "${{ toJson(github) }}" | jq '.'

