# SPDX-FileCopyrightText: 2006-2025, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2025, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Coverage

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - unlabeled
  workflow_dispatch:

concurrency:
  group: coverage-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.compiler }}
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'lint'
    strategy:
      fail-fast: false
      matrix:
        compiler: ["gcc-latest"]
    container:
      image: ghcr.io/seqan/${{ matrix.compiler }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup cache
        uses: seqan/actions/setup-actions-cache@main

      - name: Configure tests
        run: |
          mkdir build
          cd build
          cmake ../test/coverage -DCMAKE_BUILD_TYPE=Coverage
          make gtest_main

      - name: Build tests
        working-directory: build
        run: |
          ccache -z
          make -k
          ccache -sv

      - name: Run tests
        working-directory: build
        run: ctest . -j --output-on-failure --no-tests=error

      - name: Generate coverage report
        run: |
          gcovr --root ${GITHUB_WORKSPACE}/test/coverage \
                ${GITHUB_WORKSPACE}/build \
                --filter ${GITHUB_WORKSPACE}/include \
                --filter ${GITHUB_WORKSPACE}/test/include \
                --filter ${GITHUB_WORKSPACE}/src \
                --exclude ${GITHUB_WORKSPACE}/include/hibf/contrib \
                --exclude ${GITHUB_WORKSPACE}/test/include/hibf/test/iterator_test_template.hpp \
                --exclude-lines-by-pattern '^\s*}|^\s*};|.*seqan::hibf::unreachable.*' \
                --exclude-noncode-lines \
                --exclude-throw-branches \
                --exclude-unreachable-branches \
                --merge-mode-functions separate \
                -j \
                --cobertura \
                --output ${GITHUB_WORKSPACE}/build/coverage_report.xml

      - name: Submit coverage build
        uses: codecov/codecov-action@v5.4.3
        with:
          disable_search: true
          fail_ci_if_error: false
          files: build/coverage_report.xml
          plugins: noop
          token: ${{ secrets.CODECOV_TOKEN }}
